[package]
name = "blad-codec"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Lossless image codec backends for blad"

[dependencies]
thiserror.workspace = true
jpegxl-rs.workspace = true
jpegxl-sys.workspace = true
bytemuck.workspace = true
